#!/bin/bash

echo -e "\033[0mCOLOR_NC (No color)"

echo
echo -e "\033[0;30mBLACK (0)"
echo -e "\033[1;30mBRIGHT_BLACK (8)"

echo
echo -e "\033[0;31mRED (1)"
echo -e "\033[1;31mBRIGHT_RED (9)"

echo
echo -e "\033[0;32mGREEN (2)"
echo -e "\033[1;32mBRIGHT_GREEN (10)"

echo
echo -e "\033[0;33mYELLOW (3)"
echo -e "\033[1;33mBRIGHT_YELLOW (11)"

echo
echo -e "\033[0;34mBLUE (4)"
echo -e "\033[1;34mBRIGHT_BLUE (12)"

echo
echo -e "\033[0;35mMAGENTA (5)"
echo -e "\033[1;35mBRIGHT_PURPLE (13)"

echo
echo -e "\033[0;36mCYAN (6)"
echo -e "\033[1;36mBRIGHT_CYAN (14)"

echo
echo -e "\033[0;37mWHITE (7)"
echo -e "\033[1;37mBRIGHT_WHITE (15)"
