#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# TODO: put init.zsh in a better place.
if [[ -s "${ZDOTDIR:-$HOME}/workspace/dotfiles/zsh/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/workspace/dotfiles/zsh/init.zsh"
fi

# Source private settings that aren't tracked and are per-machine
# TODO: put this in a better place.
if [[ -s "${ZDOTDIR:-$HOME}/workspace/dotfiles/zsh/private.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/workspace/dotfiles/zsh/private.zsh"
fi

function hardmain() {
    git fetch --prune && git reset --hard origin/main
}

function dbr {
    git for-each-ref --format '%(refname:short)' refs/heads |
        grep -v "master\|main" |
        xargs git branch -D
}
